apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - noatime
  hostPath:
    path: /mnt/data # Путь на хосте
    type: DirectoryOrCreate # Создаст директорию, если её нет
