#login - admin password - pass
mongodb:
  nameOverride: "mongodb"
  fullnameOverride: "mongodb-deployment"
  replicaCount: 1
  image:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: mongodb-service
    type: ClusterIP
    port: 27017
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "500m"
  storage:
    size: 1Gi
    class: "mongodb-storage-class"
    hostPath: "/mnt/data"
  secret:
    name: "mongodb-secret"
    username: "dXNlcm5hbWU="
    password: "cGFzc3dvcmQ="
  configMap:
    name: "mongodb-config"
    database_url: "mongodb-service"

mongoExpress:
  nameOverride: "mongo-express"
  fullnameOverride: "mongo-express-deployment"
  replicaCount: 1
  image:
    repository: mongo-express
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: mongo-express-service
    type: NodePort
    port: 8081
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
