apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongodb.nameOverride }}-pv
spec:
  capacity:
    storage: {{ .Values.mongodb.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mongodb.storage.class }}
  hostPath:
    path: {{ .Values.mongodb.storage.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.nameOverride }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.size }}
  storageClassName: {{ .Values.mongodb.storage.class }}