apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.secret.name }}
type: Opaque
data:
  mongo-root-username: {{ .Values.mongodb.secret.username }}
  mongo-root-password: {{ .Values.mongodb.secret.password }}